language: node_js
node_js:
  - "8"

install:
  - npm install

before_script:
  - npm run installWeb3

script:
  - npm run lint
  - npm test
  - npm run coveralls

after_script:
  - sudo kill `sudo lsof -t -i:8545`

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
